### ISSUE TITLE
ipv6 support

### ISSUE THREAD

**Issue by ConnorRigby** [nerves-project/nerves_ssh#4]
Frank and I discovered that even if you have an ipv6 address, you can't access a device via ssh. After a quick search it should be as easy as adding `:inet6` to [this line](https://github.com/nerves-project/nerves_ssh/blob/master/lib/nerves_ssh.ex#L201)

**Comment by fhunleth** [comment]
PRs accepted. :trollface:

**Comment by jjcarstens** [comment]
Do you mean adding `:inet6` as a subsystem? Or adding the `{:ip_v6_disabled, false}` when starting the daemon?

**Comment by ConnorRigby** [comment]
`ip_v6_disabled` has been depreciated. The default configuration implicitly uses `:inet`, but you can specify inet6 in the list of options. My only concern is if a particular device doesn't have ipv6 enabled, I don't know what will happen. I don't think any of the default systems have ipv6 disabled, but I'm going to check anyway
